#!/user/bin/env python

# -*-coding:ENCODAGE -*

import socket
import os
import re
import getopt
import time
from blessings import Terminal

t = Terminal()

def usage():
	banner()
	print ("Usage : python scan.py HOST <options> \n")
	print "Options : "
	print "-h -- Displays this help screen"
	

def banner():
	os.system("figlet maCERT")
	print "Port Scan v 0.1 by M3µ0"
	

def getIP(hostname):
	try:
		data = socket.gethostbyname(hostname)
		ip = repr(data)
		return ip
	except Except:
		return False
